In [1]:
import pandas as pd #digunakan untuk import pandas, pandas membaca data
import numpy as np #digunakan untuk import numpy, numpy mengolah data berkaitan dengan statistika dan matematika
data=pd.read_csv("TEH1.csv")
print(data)

        TEH   MQ3   MQ4   MQ5   MQ135
0    OOLONG   563   959  2279     945
1    OOLONG   558   964  2350     951
2    OOLONG   557   998  2281     949
3    OOLONG   558   963  2293     947
4    OOLONG   555   962  2303     947
..      ...   ...   ...   ...     ...
783   HIJAU   568   703  1683     681
784   HIJAU   588   712  1687     666
785   HIJAU   594   712  1691     681
786   HIJAU   584   714  1703     691
787   HIJAU   584   714  1703     691

[788 rows x 5 columns]


In [2]:
from sklearn.preprocessing import LabelEncoder

df=pd.DataFrame(data)
X=df.iloc[:,1:5].values # Fitur
y=df.iloc[:,0].values # Target
le = LabelEncoder()

In [3]:
y=le.fit_transform(y)
print(y)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [4]:
print(X)

[[ 563  959 2279  945]
 [ 558  964 2350  951]
 [ 557  998 2281  949]
 ...
 [ 594  712 1691  681]
 [ 584  714 1703  691]
 [ 584  714 1703  691]]


In [5]:
from sklearn.model_selection import train_test_split
#membagi data training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 788 entries, 0 to 787
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   TEH     788 non-null    object
 1    MQ3    788 non-null    int64 
 2    MQ4    788 non-null    int64 
 3    MQ5    788 non-null    int64 
 4    MQ135  788 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 30.9+ KB


In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #melakukan proses transformasi menjadi normalisasi dengan rumus deviasi
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)
print(X_train_scaled)
print(X_test_scaled)

[[-0.46228218 -1.14311889 -0.72894323 -0.80910063]
 [ 1.26364272 -0.07122283 -0.73256199 -0.7568185 ]
 [-0.87688984  0.51221427  1.23965843  0.87264141]
 ...
 [-0.44299811 -1.25166533 -0.79408079 -0.90495122]
 [-0.25979937 -0.69536484 -0.73256199 -1.74146539]
 [-0.59727072 -1.29237024 -0.84112458 -1.06179763]]
[[ 1.38728272e+00  1.58279186e-01 -8.05047537e-01 -6.37829245e-01]
 [-7.96149467e-01  1.05095718e+00  1.12921237e+00  1.15680627e+00]
 [ 1.28758262e+00 -2.61804575e-01 -8.52136261e-01 -9.32600296e-01]
 [ 1.84590318e+00  9.45936238e-01 -6.56536945e-01  1.51116805e-01]
 [ 1.65647299e+00  8.14660062e-01 -6.16692640e-01 -3.86406877e-01]
 [-8.45999517e-01  1.37914762e+00  1.14007900e+00  1.43423785e+00]
 [-7.76209447e-01  5.12724859e-01  1.22338982e+00  7.66668118e-01]
 [-8.36029507e-01  4.86469624e-01  1.23063423e+00  7.40658908e-01]
 [-8.75909547e-01  1.31350953e+00  1.32118947e+00  1.32153127e+00]
 [-8.55969527e-01  1.33976476e+00  1.30307843e+00  2.64800101e+00]
 [-8.45999517e-01 

In [7]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Sesuaikan dan ubah label target
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

# Ubah label menjadi pengkodean one-hot
y_train_one_hot = tf.keras.utils.to_categorical(y_train_encoded, num_classes=3)
y_test_one_hot = tf.keras.utils.to_categorical(y_test_encoded, num_classes=3)

# Tentukan arsitektur model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=8, activation='relu', input_shape=(X_train.shape[1],))) #hidden layer 1 
#model.add(tf.keras.layers.Dense(units=4, activation='relu'))
model.add(tf.keras.layers.Dense(units=3, activation='softmax')) # Output layer

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train_one_hot, epochs=100, batch_size=128)

# Evaluate the model
evaluation_results = model.evaluate(X_test, y_test_one_hot, batch_size=128)

# Print out accuracy and all metrics
print("Evaluation results:")
for metric_name, metric_value in zip(model.metrics_names, evaluation_results):
    print(f"{metric_name}: {metric_value}")

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 118.8209 - accuracy: 0.3635
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 109.5765 - accuracy: 0.3635
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 101.4270 - accuracy: 0.3635
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 93.8402 - accuracy: 0.3635
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 86.8161 - accuracy: 0.3635
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 80.1743 - accuracy: 0.3635
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 73.8665 - accuracy: 0.3635
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 68.0499 - accuracy: 0.3635
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 62.3437 - accuracy: 0.3635
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 57.1286 - accuracy: 0.3635
Epoch 11/100
5/5

In [8]:
# Setelah pelatihan, dapatkan nilai bobot dari model
weights = model.get_weights()

# Tampilkan nilai bobot
for i, layer_weights in enumerate(weights):
    print(f'Layer {i + 1} weights:')
    print(layer_weights)

Layer 1 weights:
[[-0.26544303 -0.4462884   0.00772822  0.13964516 -0.03067335 -0.1722004
  -0.31178433 -0.07587592]
 [-0.64973027 -0.25213188 -0.2128033  -0.08379555 -0.5608912  -0.57728493
   0.4991321   0.04514279]
 [ 0.39783877 -0.42221364 -0.37912354  0.01432973 -0.01194285  0.36636084
  -0.16570103  0.1140129 ]
 [-0.542084    0.01079583 -0.25007394 -0.5433398   0.5526142  -0.06789885
  -0.555428    0.2609561 ]]
Layer 2 weights:
[ 0.          0.          0.          0.         -0.0318482  -0.05831
  0.         -0.10218678]
Layer 3 weights:
[[ 0.29818076  0.47195476  0.6544779 ]
 [-0.60316813 -0.6792615  -0.6616729 ]
 [ 0.34649938  0.5892964  -0.5958184 ]
 [-0.0305081  -0.73845595  0.24170953]
 [-0.6725815  -0.09072246 -0.40182707]
 [-0.15099682 -0.5717467  -0.0607877 ]
 [-0.14493859  0.33809906  0.5858061 ]
 [-0.43933553 -0.42921948 -0.45787075]]
Layer 4 weights:
[ 0.09695532  0.21801533 -0.17635295]


In [10]:
manual_data = np.array([[786,883,1757,732]])

classes = ['Hijau', 'Hitam', 'Oolong']

# Lakukan prediksi dengan model
predictions = model.predict(manual_data)

# Dapatkan indeks kelas dengan probabilitas tertinggi untuk setiap prediksi
predicted_classes = np.argmax(predictions, axis=1)

# Inisialisasi LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(classes)

# Konversi kelas yang diprediksi menjadi nama kelas yang sesuai
predicted_classes_names = label_encoder.inverse_transform(predicted_classes)

# Print hasil prediksi
print("Hasil prediksi untuk angka manual:", predicted_classes_names)

1/1 [==============================] - 0s 19ms/step
Hasil prediksi untuk angka manual: ['Hitam']


In [10]:
# Print out accuracy and all metrics
print("Evaluation results:")
for metric_name, metric_value in zip(model.metrics_names, evaluation_results):
    print(f"{metric_name}: {metric_value}")

Evaluation results:
loss: 1.2711985111236572
accuracy: 0.8734177350997925


In [48]:
#JOBLIB
import joblib

joblib.dump(model, 'classification_model.joblib')


Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........2
.........3
.........4
.........5
.........6
.........7
.........8
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2024-03-20 10:47:42         1407
metadata.json                                  2024-03-20 10:47:42           64
variables.h5                                   2024-03-20 10:47:42        19424


['classification_model.joblib']

In [52]:
from sklearn.metrics import accuracy_score
annjl = joblib.load('classification_model.joblib')
y_pred = annjl.predict(X_test)



Keras model archive loading:
File Name                                             Modified             Size
config.json                                    2024-03-20 10:47:42         1407
metadata.json                                  2024-03-20 10:47:42           64
variables.h5                                   2024-03-20 10:47:42        19424


Keras weights file (<HDF5 file "variables.h5" (mode r)>) loading:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........2
.........3
.........4
.........5
.........6
.........7
.........8
...vars
5/5 [==============================] - 0s 4ms/step
loss: 0.12550775706768036
accuracy: 0.9556962251663208
